### ISSUE TITLE
CSS stopped working

### ISSUE THREAD

**Issue by warpaltarpers** [photonfighterlabs/assassin-tracker#3]
#### What is the issue/bug?
* The CSS (notably in the page-header) isn't showing correctly.

#### What were you doing that caused the bug? (*please be as descriptive as possible*)  
* After we merged #2, the CSS doesn't seem to work when opened through the Heroku link

**Comment by warpaltarpers** [comment]
If you open application.html.erb locally, the CSS from main.css works

**Comment by photonfighter** [comment]
Issue with directory for css file, rails doesn't need anything up to (and including) the public folder.
